name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Application
        run: pyinstaller --onefile Calculator.py

      - name: Static Analysis
        run: |
          pylint --output-format=text Calculator.py > pylint_report.txt ; exit 0

      - name: Code Style Check
        run: |
          pycodestyle Calculator.py > pycodestyle_report.txt ; exit 0

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: calculator-artifact
          path: |
            dist/
            pylint_report.txt
            pycodestyle_report.txt
